### ISSUE TITLE
chat pipeline doesnt work

### ISSUE THREAD

**Issue by vince-p** [Orciotrox/Nano-GPT_OpenWebUI_Functions#2]
I have added GPT pipeline function and can now see all the nano-gpt models, but whenever I try to start a chat (for any nano-gpt model) I get the following error:

Error from API: {"message":"Failed to talk to model","code":"unknown_error","error":{},"status":500}

**Comment by vince-p** [comment]
After updating to openwebui 0.52, I changed this line:
from open_webui.main import chat_completion_tools_handler

to
from open_webui.main import chat_completion

as advised here:
https://docs.openwebui.com/features/plugin/migration/

Now I get a different error:
Error from API: error: {"error":"Cannot read properties of undefined (reading 'disabled')"}

Could you please advise how to get this working - I'd really like to link these services.
I appreciate your time, thanks

**Comment by SenatusSPQR1** [comment]
I think this should fix it: https://github.com/Orciotrox/Nano-GPT_OpenWebUI_Functions/pull/3/files.

**Comment by vince-p** [comment]
The fix by @SenatusSPQR1 didn't fix the issue directly, but did help me work out a fix which is in #5

**Comment by vince-p** [comment]
I've discovered another critical issue with this script. There is no retention of chat history. Each part of the conversation is as if it is a new chat. See:
![image](https://github.com/user-attachments/assets/254754ac-dc01-461d-8c8c-8186a499728f)
